-- Tao bang nhanvien
CREATE TABLE NHAN_VIEN(
	MA_NV INT AUTO_INCREMENT PRIMARY KEY,
    TEN_NV VARCHAR(100) NOT NULL,
    CHUC_VU VARCHAR(50),
    LUONG DECIMAL(10,2)
);

-- tao bang tour
CREATE TABLE TOUR(
	MA_TOUR INT AUTO_INCREMENT PRIMARY KEY,
    TEN_TOUR VARCHAR(100) NOT NULL,
    DIA_DIEM VARCHAR(100),
    GIA DECIMAL(12,2),
    SO_NGAY INT,
    MA_NV INT,
    FOREIGN KEY (MA_NV) REFERENCES  NHAN_VIEN(MA_NV)
);

-- tao bang khachhang
CREATE TABLE KHACH_HANG(
	MA_KH INT AUTO_INCREMENT PRIMARY KEY,
	TEN_KH VARCHAR(100) NOT NULL,
	SDT VARCHAR(15),
	EMAIL VARCHAR(100),
	DIA_CHI VARCHAR(200)
);

-- tao bang dat tour
CREATE TABLE DAT_TOUR(
	MA_DAT INT AUTO_INCREMENT PRIMARY KEY,
    MA_KH INT,
    MA_TOUR INT,
    NGAY_DAT DATE,
    SO_NGUOI INT,
    FOREIGN KEY (MA_KH) REFERENCES KHACH_HANG(MA_KH),
    FOREIGN KEY (MA_TOUR) REFERENCES TOUR(MA_TOUR)
);

-- tao bang thanhtoan
CREATE TABLE THANH_TOAN(
	MA_TT INT AUTO_INCREMENT PRIMARY KEY,
    MA_DAT INT,
    NGAY_TT DATE,
    SO_TIEN DECIMAL(10,2),
    PHUONG_THUC VARCHAR(50),
    FOREIGN KEY (MA_DAT) REFERENCES DAT_TOUR(MA_DAT)
);
    